import { boolean, pgTable, primaryKey, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const authUser = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("user_email_idx").on(table.email)]);
export const authSession = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), token: text("token").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }) }, (table) => [uniqueIndex("session_token_idx").on(table.token)]);
export const authAccount = pgTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), idToken: text("id_token"), password: text("password"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("account_provider_idx").on(table.providerId, table.accountId)]);
export const authVerification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("verification_identifier_idx").on(table.identifier)]);
export const userProfiles = pgTable("user_profile", { userId: text("user_id").primaryKey().references(() => authUser.id, { onDelete: "cascade" }), role: text("role").notNull().default("Viewer"), status: text("status").notNull().default("invited"), lastActive: text("last_active").notNull().default("Not yet") });
export const roles = pgTable("role", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull(), system: boolean("system").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("role_name_idx").on(table.name)]);
export const permissions = pgTable("permission", { key: text("key").primaryKey(), description: text("description").notNull() });
export const rolePermissions = pgTable("role_permission", { roleId: text("role_id").notNull().references(() => roles.id, { onDelete: "cascade" }), permissionKey: text("permission_key").notNull().references(() => permissions.key, { onDelete: "cascade" }) }, (table) => [primaryKey({ columns: [table.roleId, table.permissionKey] })]);
export const userRoles = pgTable("user_role", { userId: text("user_id").notNull().references(() => authUser.id, { onDelete: "cascade" }), roleId: text("role_id").notNull().references(() => roles.id, { onDelete: "cascade" }) }, (table) => [primaryKey({ columns: [table.userId, table.roleId] })]);
export const auditLogs = pgTable("audit_log", { id: text("id").primaryKey(), actorId: text("actor_id").references(() => authUser.id, { onDelete: "set null" }), action: text("action").notNull(), resourceType: text("resource_type").notNull(), resourceId: text("resource_id"), metadata: text("metadata"), ipAddress: text("ip_address"), userAgent: text("user_agent"), requestId: text("request_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export type AuthUser = typeof authUser.$inferSelect;
export type Role = typeof roles.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
